<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_7";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
                "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'Skeleton code', 1)",
                "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'for homework1', 1)",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CUSTOMER (id, password, email, name, phone) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'hola', 'papi@gmail.com', 'Papi', '666572992')",
                "INSERT INTO " + schema + ".CUSTOMER (id, password, email, name, phone) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'tonto', 'pepe@gmail.com', 'sob', '666534562')",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'GTA VI', 'PS5', 1, 15.95, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 10)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'Mario Bros', 'NDS', 1, 5.00, 'Divertido', 'Arcade', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 1)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'Assasins Creed', 'NDS', 1, 6.49, 'Entretenido', 'Adventure', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 3)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'FIFA15', 'PS4', 1, 2.99, 'Guay', 'FURBO', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 5)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'Farcry3', 'PS4', 1, 1.67, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 5)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'WIISports', 'WII', 1, 2.50, 'Guay', 'Sports', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 4)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'Zelda', 'Switch', 1, 2.99, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 2)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'MarioParty8', 'NDS', 1, 3.99, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 1)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'Minecraft', 'Switch', 1, 2.99, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 99)",
                "INSERT INTO " + schema + ".GAME (id, name, console, availability, weeklyRentalPrice, description, gameType, pickupLocationAddress, counter) VALUES (NEXT VALUE FOR GAME_GEN, 'MarioKart', 'Switch', 1, 2.99, 'Guay', 'Action', 'The Retro Games Store, pl. del Blat 3, Valls, 43800', 1)"
               
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
